# Basic settings
title: "N0p Blog"
description: ""
baseurl: "" 
url: "https://n0pps.github.io/" 

# Author settings
author:
  name: "N0p"
  email: ""

# Markdown and permalink settings
markdown: kramdown
permalink: /:categories/:title/
timezone: "Europe/Lisbon" 

# Directory settings
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title.html

# Theme and design settings
sass:
  style: compressed
include: ["_pages"]
exclude: ["Gemfile", "Gemfile.lock", "README.md", ".gitignore", ".jekyll-cache"]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Menu items
menu:
  home: "/"
  about: "/whoami"
  posts: "/posts/"

# Build settings
markdown_ext: "markdown,mkdn,mkdn,mkdown,md"
highlighter: rouge
